print("================================")
print("        ERA AI v0.1")
print("================================")
print("System Starting...")
print("Brain Loaded")
print("Memory Loaded")
print("Research Loaded")
print("Logger Loaded")
print("ERA AI Ready")
