"""Self-hosted browser automation with Playwright and an offline simulator.

The provider owns the ``browser.*`` action family while the existing execution
service remains the only dispatch boundary.  Consequently every navigation,
DOM read and interaction still passes through permission evaluation,
confirmation, audit-before-execute, timeout/retry and circuit-breaker gates.

Security properties implemented here:

* every top-level navigation is checked with :func:`validate_public_url` both
  during validation and immediately before dispatch;
* the Playwright transport intercepts subresource/redirect requests and blocks
  non-public HTTP(S), non-network schemes and WebSockets;
* each ``(actor_id, session_id)`` gets a separate non-persistent browser
  context (no shared cookies, local storage or cache);
* screenshots and optional HTML dumps are written by this provider only after
  :class:`WorkspaceRoot` containment checks;
* configured viewport and per-operation timeout bounds are applied inside
  Playwright as well as at ERA's provider dispatch boundary;
* Playwright is imported lazily.  Offline CI can inject
  :class:`SimulatedBrowserTransport` without installing Chromium or opening a
  socket.
"""

from __future__ import annotations

import hashlib
import queue
import re
import threading
import time
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path
from typing import Any, Protocol
from urllib.parse import urljoin, urlsplit

from era.core.action import Action
from era.core.context import ExecutionContext
from era.core.provider_info import ProviderInfo
from era.core.result import ActionResult, ProviderErrorCode, ToolError
from era.registry.actions import ActionType
from era.security.path_safety import WorkspaceRoot
from era.security.url_safety import validate_public_url
from era.security.vault import VaultError, is_vault_ref, parse_vault_ref

DEFAULT_TIMEOUT_SECONDS = 30.0
DEFAULT_VIEWPORT_WIDTH = 1280
DEFAULT_VIEWPORT_HEIGHT = 800
DEFAULT_USER_AGENT = "ERA-Agent/0.8.1 (+https://github.com/sajanji15859-cmyk/ERA-AI)"
MAX_DOM_CHARS = 100_000
DEFAULT_DOM_CHARS = 50_000
MAX_DOM_SOURCE_CHARS = 2_000_000
MAX_SCREENSHOT_BYTES = 20 * 1024 * 1024
MAX_LINKS = 200
DEFAULT_MAX_CONTEXTS = 32
DEFAULT_CONTEXT_IDLE_SECONDS = 300.0
DEFAULT_COMMAND_QUEUE_SIZE = 128
_DISPATCH_SAFETY_MARGIN_SECONDS = 0.25

_NON_RETRYABLE_ACTION_TYPES = frozenset({
    ActionType.BROWSER_CLICK.value,
    ActionType.BROWSER_FILL.value,
    ActionType.BROWSER_SUBMIT.value,
})
_NON_RETRYABLE_OPERATIONS = frozenset({"click", "fill", "submit"})

_ACTION_TYPES = frozenset({
    ActionType.BROWSER_NAVIGATE.value,
    ActionType.BROWSER_SCREENSHOT.value,
    ActionType.BROWSER_EXTRACT_DOM.value,
    ActionType.BROWSER_CLICK.value,
    ActionType.BROWSER_FILL.value,
    ActionType.BROWSER_SUBMIT.value,
})

# A valid deterministic one-pixel PNG used only by the explicit offline
# simulator.  Production screenshots always come from Chromium.
_SIMULATED_PNG = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
    b"\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\rIDAT\x08\xd7c\xf8"
    b"\xcf\xc0\xf0\x1f\x00\x05\x00\x01\xff\x89\x99=\x1d\x00\x00\x00\x00IEND"
    b"\xaeB`\x82"
)


class BrowserTransport(Protocol):
    """Modular browser engine interface used by production and offline tests."""

    def navigate(self, session_key: str, url: str, *, wait_until: str,
                 timeout_ms: int) -> dict[str, Any]: ...

    def screenshot(self, session_key: str, *, selector: str | None,
                   full_page: bool, image_type: str, timeout_ms: int) -> bytes: ...

    def extract(self, session_key: str, *, selector: str | None,
                timeout_ms: int) -> dict[str, Any]: ...

    def click(self, session_key: str, *, selector: str | None, text: str | None,
              exact: bool, timeout_ms: int) -> dict[str, Any]: ...

    def fill(self, session_key: str, *, selector: str, text: str,
             timeout_ms: int) -> dict[str, Any]: ...

    def submit(self, session_key: str, *, selector: str | None,
               timeout_ms: int) -> dict[str, Any]: ...

    def close_context(self, session_key: str) -> None: ...

    def close(self) -> None: ...


def guard_browser_request(url: str) -> None:
    """Apply browser-network SSRF policy to one outgoing request.

    Chromium-internal, extension, file and WebSocket schemes are never allowed.
    ``data:``, ``blob:`` and ``about:blank`` may be generated by an already
    approved public document and do not create a network connection.
    """

    try:
        scheme = urlsplit(url).scheme.lower()
    except ValueError as exc:
        raise ToolError("invalid browser request URL", provider_id="browser",
                        code=ProviderErrorCode.FORBIDDEN) from exc
    if scheme in {"data", "blob"} or url == "about:blank":
        return
    if scheme not in {"http", "https"}:
        raise ToolError("browser request scheme is blocked", provider_id="browser",
                        code=ProviderErrorCode.FORBIDDEN)
    validate_public_url(url)


@dataclass
class _SimulatedSession:
    url: str
    html: str
    title: str = ""
    fields: dict[str, str] = field(default_factory=dict)
    clicks: list[dict[str, Any]] = field(default_factory=list)
    submitted: bool = False


class SimulatedBrowserTransport:
    """Deterministic in-memory browser transport for offline tests/CI.

    The simulator performs no DNS or network calls itself.  The provider's URL
    guard still runs before ``navigate``; tests normally use a public IP literal
    or monkeypatch DNS resolution.  Session state is isolated by the opaque key
    supplied by :class:`BrowserProvider`.
    """

    def __init__(self, pages: dict[str, str] | None = None):
        self.pages = dict(pages or {})
        self.sessions: dict[str, _SimulatedSession] = {}
        self.closed = False

    def navigate(self, session_key: str, url: str, *, wait_until: str,
                 timeout_ms: int) -> dict[str, Any]:
        del wait_until, timeout_ms
        if url not in self.pages:
            raise ToolError("simulated page not found", provider_id="browser",
                            code=ProviderErrorCode.NOT_FOUND)
        html = self.pages[url]
        title = _title_from_html(html)
        self.sessions[session_key] = _SimulatedSession(url=url, html=html, title=title)
        return {"url": url, "title": title, "status": 200}

    def screenshot(self, session_key: str, *, selector: str | None,
                   full_page: bool, image_type: str, timeout_ms: int) -> bytes:
        del selector, full_page, image_type, timeout_ms
        self._session(session_key)
        return _SIMULATED_PNG

    def extract(self, session_key: str, *, selector: str | None,
                timeout_ms: int) -> dict[str, Any]:
        del selector, timeout_ms
        session = self._session(session_key)
        text = _plain_text_from_html(session.html)
        return {
            "url": session.url,
            "title": session.title,
            "html": session.html,
            "text": text,
        }

    def click(self, session_key: str, *, selector: str | None, text: str | None,
              exact: bool, timeout_ms: int) -> dict[str, Any]:
        del timeout_ms
        session = self._session(session_key)
        session.clicks.append({"selector": selector, "text": text, "exact": exact})
        return {"url": session.url, "title": session.title}

    def fill(self, session_key: str, *, selector: str, text: str,
             timeout_ms: int) -> dict[str, Any]:
        del timeout_ms
        session = self._session(session_key)
        session.fields[selector] = text
        return {"url": session.url, "title": session.title}

    def submit(self, session_key: str, *, selector: str | None,
               timeout_ms: int) -> dict[str, Any]:
        del selector, timeout_ms
        session = self._session(session_key)
        session.submitted = True
        return {"url": session.url, "title": session.title}

    def close_context(self, session_key: str) -> None:
        self.sessions.pop(session_key, None)

    def close(self) -> None:
        self.sessions.clear()
        self.closed = True

    def _session(self, session_key: str) -> _SimulatedSession:
        session = self.sessions.get(session_key)
        if session is None:
            raise ToolError("browser context has no open page", provider_id="browser",
                            code=ProviderErrorCode.NOT_FOUND)
        return session


@dataclass
class _BrowserCommand:
    operation: str
    session_key: str
    kwargs: dict[str, Any]
    response: queue.Queue[tuple[bool, Any]]
    deadline: float
    cancelled: threading.Event = field(default_factory=threading.Event)


@dataclass
class _PlaywrightSession:
    context: Any
    page: Any
    last_used: float


class PlaywrightBrowserTransport:
    """Headless Chromium transport hosted on one dedicated worker thread.

    Playwright's synchronous objects are thread-affine, while ERA's hard
    timeout boundary invokes provider calls on short-lived worker threads.  A
    dedicated command thread keeps every Browser/Context/Page operation on the
    same owner thread and lets arbitrary ERA dispatch threads safely submit
    bounded operations.
    """

    def __init__(self, *, headless: bool = True,
                 viewport_width: int = DEFAULT_VIEWPORT_WIDTH,
                 viewport_height: int = DEFAULT_VIEWPORT_HEIGHT,
                 user_agent: str = DEFAULT_USER_AGENT,
                 max_contexts: int = DEFAULT_MAX_CONTEXTS,
                 context_idle_seconds: float = DEFAULT_CONTEXT_IDLE_SECONDS,
                 command_queue_size: int = DEFAULT_COMMAND_QUEUE_SIZE,
                 proxy_server: str = ""):
        if int(max_contexts) < 1:
            raise ValueError("browser max_contexts must be positive")
        if float(context_idle_seconds) <= 0:
            raise ValueError("browser context_idle_seconds must be positive")
        if int(command_queue_size) < 1:
            raise ValueError("browser command_queue_size must be positive")
        proxy_server = proxy_server.strip()
        if proxy_server:
            proxy = urlsplit(proxy_server)
            if proxy.scheme not in {"http", "https", "socks5"} or not proxy.hostname:
                raise ValueError("browser proxy_server must be an HTTP(S) or SOCKS5 URL")
            if proxy.username is not None or proxy.password is not None:
                raise ValueError("browser proxy credentials must not be embedded in the URL")
        self.headless = bool(headless)
        self.viewport_width = int(viewport_width)
        self.viewport_height = int(viewport_height)
        self.user_agent = user_agent
        self.max_contexts = int(max_contexts)
        self.context_idle_seconds = float(context_idle_seconds)
        self.proxy_server = proxy_server
        self._commands: queue.Queue[_BrowserCommand | None] = queue.Queue(
            maxsize=int(command_queue_size),
        )
        self._start_lock = threading.Lock()
        self._thread: threading.Thread | None = None
        self._stop = threading.Event()
        self._closed = False
        self._playwright = None
        self._browser = None
        self._contexts: dict[str, _PlaywrightSession] = {}

    def navigate(self, session_key: str, url: str, *, wait_until: str,
                 timeout_ms: int) -> dict[str, Any]:
        return self._call("navigate", session_key, timeout_ms=timeout_ms,
                          url=url, wait_until=wait_until)

    def screenshot(self, session_key: str, *, selector: str | None,
                   full_page: bool, image_type: str, timeout_ms: int) -> bytes:
        return self._call("screenshot", session_key, timeout_ms=timeout_ms,
                          selector=selector, full_page=full_page, image_type=image_type)

    def extract(self, session_key: str, *, selector: str | None,
                timeout_ms: int) -> dict[str, Any]:
        return self._call("extract", session_key, timeout_ms=timeout_ms,
                          selector=selector)

    def click(self, session_key: str, *, selector: str | None, text: str | None,
              exact: bool, timeout_ms: int) -> dict[str, Any]:
        return self._call("click", session_key, timeout_ms=timeout_ms,
                          selector=selector, text=text, exact=exact)

    def fill(self, session_key: str, *, selector: str, text: str,
             timeout_ms: int) -> dict[str, Any]:
        return self._call("fill", session_key, timeout_ms=timeout_ms,
                          selector=selector, text=text)

    def submit(self, session_key: str, *, selector: str | None,
               timeout_ms: int) -> dict[str, Any]:
        return self._call("submit", session_key, timeout_ms=timeout_ms,
                          selector=selector)

    def close_context(self, session_key: str) -> None:
        if self._thread is None or self._closed:
            return
        self._call("close_context", session_key, timeout_ms=5_000)

    def close(self) -> None:
        with self._start_lock:
            if self._closed:
                return
            self._closed = True
            self._stop.set()
            thread = self._thread
            if thread is None:
                return
            try:
                self._commands.put_nowait(None)
            except queue.Full:
                pass  # worker observes _stop after the in-flight command
        thread.join(timeout=5.0)

    def _ensure_started(self) -> None:
        with self._start_lock:
            if self._closed:
                raise ToolError("browser transport is closed", provider_id="browser",
                                code=ProviderErrorCode.UNAVAILABLE)
            if self._thread is None:
                self._thread = threading.Thread(
                    target=self._worker, name="era-browser-playwright", daemon=True,
                )
                self._thread.start()

    def _call(self, operation: str, session_key: str, *, timeout_ms: int,
              **kwargs: Any) -> Any:
        self._ensure_started()
        timeout_seconds = max(0.001, timeout_ms / 1000)
        deadline = time.monotonic() + timeout_seconds
        response: queue.Queue[tuple[bool, Any]] = queue.Queue(maxsize=1)
        kwargs["timeout_ms"] = timeout_ms
        command = _BrowserCommand(
            operation, session_key, kwargs, response, deadline=deadline,
        )
        try:
            self._commands.put(command, timeout=timeout_seconds)
        except queue.Full as exc:
            command.cancelled.set()
            raise ToolError("browser command queue is full", provider_id="browser",
                            code=ProviderErrorCode.UNAVAILABLE) from exc
        remaining = max(0.001, deadline - time.monotonic())
        try:
            # Small grace lets the worker report its own deadline classification
            # while the provider's outer dispatch deadline remains authoritative.
            ok, value = response.get(timeout=remaining + 0.05)
        except queue.Empty as exc:
            command.cancelled.set()
            code = (
                ProviderErrorCode.SIDE_EFFECT_UNKNOWN
                if operation in _NON_RETRYABLE_OPERATIONS
                else ProviderErrorCode.TIMEOUT
            )
            raise ToolError("browser operation timed out", provider_id="browser",
                            code=code) from exc
        if ok:
            return value
        raise _transport_error(value)

    def _worker(self) -> None:
        poll_seconds = min(1.0, self.context_idle_seconds)
        while not self._stop.is_set():
            try:
                command = self._commands.get(timeout=poll_seconds)
            except queue.Empty:
                self._reap_idle_contexts()
                continue
            if command is None:
                break
            if command.cancelled.is_set() or time.monotonic() >= command.deadline:
                command.response.put((False, ToolError(
                    "browser command expired before dispatch",
                    provider_id="browser", code=ProviderErrorCode.TIMEOUT,
                )))
                continue
            try:
                self._ensure_runtime()
                value = self._dispatch(command)
            except BaseException as exc:  # noqa: BLE001 - returned to dispatch thread
                error = self._command_error(command, exc)
                command.response.put((False, error))
            else:
                if command.operation in _NON_RETRYABLE_OPERATIONS and (
                    command.cancelled.is_set() or time.monotonic() >= command.deadline
                ):
                    self._close_session(command.session_key)
                    command.response.put((False, ToolError(
                        "browser interaction outcome is unknown after timeout",
                        provider_id="browser",
                        code=ProviderErrorCode.SIDE_EFFECT_UNKNOWN,
                    )))
                else:
                    command.response.put((True, value))
            session = self._contexts.get(command.session_key)
            if session is not None:
                session.last_used = time.monotonic()
            self._reap_idle_contexts()
        self._shutdown_runtime()

    def _ensure_runtime(self) -> None:
        if self._browser is not None:
            return
        try:
            from playwright.sync_api import sync_playwright
        except ImportError as exc:
            raise ToolError(
                "Playwright is not installed; install ERA with the browser extra",
                provider_id="browser", code=ProviderErrorCode.NOT_IMPLEMENTED,
            ) from exc
        self._playwright = sync_playwright().start()
        launch_options: dict[str, Any] = {
            "headless": self.headless,
            "args": [
                "--disable-quic",
                "--force-webrtc-ip-handling-policy=disable_non_proxied_udp",
            ],
        }
        if self.proxy_server:
            launch_options["proxy"] = {"server": self.proxy_server}
        self._browser = self._playwright.chromium.launch(**launch_options)

    def _context_page(self, session_key: str) -> tuple[Any, Any]:
        session = self._contexts.get(session_key)
        if session is not None:
            session.last_used = time.monotonic()
            return session.context, session.page
        self._reap_idle_contexts()
        if len(self._contexts) >= self.max_contexts:
            raise ToolError(
                "browser context limit reached",
                provider_id="browser", code=ProviderErrorCode.UNAVAILABLE,
            )
        context = self._browser.new_context(
            viewport={"width": self.viewport_width, "height": self.viewport_height},
            user_agent=self.user_agent,
            accept_downloads=False,
            service_workers="block",
        )
        context.route("**/*", self._guard_route)
        # WebSocket handshakes have historically bypassed regular request
        # routing. Disable them rather than risk private-network access.
        context.add_init_script(
            "Object.defineProperty(window, 'WebSocket', {value: class {"
            "constructor(){throw new Error('WebSocket blocked by ERA policy')}}});"
        )
        page = context.new_page()
        self._contexts[session_key] = _PlaywrightSession(
            context=context, page=page, last_used=time.monotonic(),
        )
        return context, page

    @staticmethod
    def _guard_route(route: Any, request: Any) -> None:
        try:
            guard_browser_request(request.url)
        except ToolError:
            route.abort("blockedbyclient")
        else:
            route.continue_()

    def _dispatch(self, command: _BrowserCommand) -> Any:
        operation = command.operation
        if operation == "close_context":
            session = self._contexts.pop(command.session_key, None)
            if session is not None:
                session.context.close()
            return None

        _, page = self._context_page(command.session_key)
        kwargs = command.kwargs
        remaining_ms = max(1, int((command.deadline - time.monotonic()) * 1000))
        timeout_ms = min(int(kwargs.get("timeout_ms", 30_000)), remaining_ms)
        page.set_default_timeout(timeout_ms)
        page.set_default_navigation_timeout(timeout_ms)

        if operation == "navigate":
            response = page.goto(
                kwargs["url"], wait_until=kwargs["wait_until"], timeout=timeout_ms,
            )
            guard_browser_request(page.url)
            return {
                "url": page.url,
                "title": page.title(),
                "status": response.status if response is not None else None,
            }
        if operation == "screenshot":
            selector = kwargs.get("selector")
            if selector:
                return page.locator(selector).first.screenshot(
                    type=kwargs["image_type"], timeout=timeout_ms,
                )
            return page.screenshot(
                full_page=bool(kwargs["full_page"]),
                type=kwargs["image_type"], timeout=timeout_ms,
            )
        if operation == "extract":
            selector = kwargs.get("selector")
            if selector:
                locator = page.locator(selector).first
                html = locator.evaluate("element => element.outerHTML")
                text = locator.inner_text(timeout=timeout_ms)
            else:
                html = page.content()
                text = page.locator("body").inner_text(timeout=timeout_ms)
            return {"url": page.url, "title": page.title(), "html": html, "text": text}
        if operation == "click":
            selector = kwargs.get("selector")
            if selector:
                page.locator(selector).first.click(timeout=timeout_ms)
            else:
                page.get_by_text(kwargs["text"], exact=bool(kwargs["exact"])).first.click(
                    timeout=timeout_ms,
                )
            self._guard_current_page(page)
            return {"url": page.url, "title": page.title()}
        if operation == "fill":
            page.locator(kwargs["selector"]).first.fill(kwargs["text"], timeout=timeout_ms)
            return {"url": page.url, "title": page.title()}
        if operation == "submit":
            selector = kwargs.get("selector") or "form"
            page.locator(selector).first.evaluate(
                "element => {"
                "const form = element.tagName === 'FORM' ? element : "
                "(element.form || element.closest('form'));"
                "if (!form) throw new Error('element is not associated with a form');"
                "if (form.requestSubmit) form.requestSubmit(); else form.submit();"
                "}",
            )
            self._guard_current_page(page)
            return {"url": page.url, "title": page.title()}
        raise ToolError("unsupported browser transport operation", provider_id="browser",
                        code=ProviderErrorCode.NOT_IMPLEMENTED)

    @staticmethod
    def _guard_current_page(page: Any) -> None:
        if page.url and page.url != "about:blank":
            guard_browser_request(page.url)

    def _command_error(self, command: _BrowserCommand, exc: BaseException) -> ToolError:
        error = _transport_error(exc)
        if command.operation in _NON_RETRYABLE_OPERATIONS \
                and error.code is ProviderErrorCode.TIMEOUT:
            # Chromium may have delivered the interaction before its wait timed
            # out. Never report a clean TIMEOUT (which implies no side effect),
            # and quarantine all resulting page/cookie state.
            self._close_session(command.session_key)
            return ToolError(
                "browser interaction outcome is unknown after timeout",
                provider_id="browser",
                code=ProviderErrorCode.SIDE_EFFECT_UNKNOWN,
            )
        return error

    def _close_session(self, session_key: str) -> None:
        session = self._contexts.pop(session_key, None)
        if session is None:
            return
        try:
            session.context.close()
        except Exception:  # noqa: BLE001,S110 - fail-closed cleanup
            pass

    def _reap_idle_contexts(self) -> None:
        cutoff = time.monotonic() - self.context_idle_seconds
        expired = [
            key for key, session in self._contexts.items()
            if session.last_used <= cutoff
        ]
        for key in expired:
            self._close_session(key)

    def _shutdown_runtime(self) -> None:
        for key in list(self._contexts):
            self._close_session(key)
        self._contexts.clear()
        if self._browser is not None:
            try:
                self._browser.close()
            except Exception:  # noqa: BLE001,S110
                pass
        if self._playwright is not None:
            try:
                self._playwright.stop()
            except Exception:  # noqa: BLE001,S110
                pass


def _transport_error(exc: BaseException) -> ToolError:
    if isinstance(exc, ToolError):
        return exc
    name = type(exc).__name__.lower()
    message = str(exc).lower()
    if "timeout" in name:
        code = ProviderErrorCode.TIMEOUT
        safe_message = "browser operation timed out"
    elif "executable doesn't exist" in message or "browser executable" in message:
        code = ProviderErrorCode.NOT_IMPLEMENTED
        safe_message = "Chromium is not installed; run 'playwright install chromium'"
    else:
        code = ProviderErrorCode.PROVIDER_ERROR
        safe_message = f"browser engine error: {type(exc).__name__}"
    return ToolError(safe_message, provider_id="browser", code=code)


class BrowserProvider:
    """ERA ToolProvider implementing the six catalogued browser actions."""

    id = "browser"
    action_types = _ACTION_TYPES
    # ExecutionService and AgentLoop both consult this declaration. Transport
    # errors or failed post-condition checks must never repeat these effects.
    non_retryable_action_types = _NON_RETRYABLE_ACTION_TYPES

    def __init__(self, *, workspace_root: str | Path,
                 transport: BrowserTransport | None = None,
                 headless: bool = True,
                 timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
                 viewport_width: int = DEFAULT_VIEWPORT_WIDTH,
                 viewport_height: int = DEFAULT_VIEWPORT_HEIGHT,
                 user_agent: str = DEFAULT_USER_AGENT,
                 max_contexts: int = DEFAULT_MAX_CONTEXTS,
                 context_idle_seconds: float = DEFAULT_CONTEXT_IDLE_SECONDS,
                 command_queue_size: int = DEFAULT_COMMAND_QUEUE_SIZE,
                 proxy_server: str = "",
                 secret_resolver: Any | None = None):
        if float(timeout_seconds) <= 0:
            raise ValueError("browser timeout_seconds must be positive")
        if int(viewport_width) <= 0 or int(viewport_height) <= 0:
            raise ValueError("browser viewport dimensions must be positive")
        if not isinstance(user_agent, str) or not user_agent.strip():
            raise ValueError("browser user_agent must be non-empty")
        self.workspace = WorkspaceRoot(workspace_root)
        self.timeout_seconds = float(timeout_seconds)
        self.viewport_width = int(viewport_width)
        self.viewport_height = int(viewport_height)
        self.user_agent = user_agent
        self.headless = bool(headless)
        self._secret_resolver = secret_resolver
        self.transport = transport or PlaywrightBrowserTransport(
            headless=self.headless,
            viewport_width=self.viewport_width,
            viewport_height=self.viewport_height,
            user_agent=self.user_agent,
            max_contexts=max_contexts,
            context_idle_seconds=context_idle_seconds,
            command_queue_size=command_queue_size,
            proxy_server=proxy_server,
        )

    def validate(self, action: Action) -> None:
        params = action.params or {}
        action_type = action.action_type
        if action_type not in self.action_types:
            raise ToolError(f"browser cannot handle {action_type}", provider_id=self.id,
                            code=ProviderErrorCode.NOT_IMPLEMENTED)

        if action_type == ActionType.BROWSER_NAVIGATE.value:
            url = _required_string(params, "url", self.id)
            validate_public_url(url)
            wait_until = params.get("wait_until", "domcontentloaded")
            if wait_until not in {"commit", "domcontentloaded", "load", "networkidle"}:
                raise ToolError("invalid wait_until value", provider_id=self.id,
                                code=ProviderErrorCode.VALIDATION)
            return

        if action_type == ActionType.BROWSER_SCREENSHOT.value:
            path = _required_string(params, "path", self.id)
            resolved = self.workspace.resolve(path)
            if resolved.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
                raise ToolError("screenshot path must end in .png, .jpg or .jpeg",
                                provider_id=self.id, code=ProviderErrorCode.VALIDATION)
            selector = params.get("selector")
            _optional_string(selector, "selector", self.id)
            if selector and params.get("full_page", False):
                raise ToolError("element screenshots cannot use full_page",
                                provider_id=self.id, code=ProviderErrorCode.VALIDATION)
            return

        if action_type == ActionType.BROWSER_EXTRACT_DOM.value:
            _optional_string(params.get("selector"), "selector", self.id)
            max_chars = params.get("max_chars", DEFAULT_DOM_CHARS)
            if not isinstance(max_chars, int) or isinstance(max_chars, bool) \
                    or not 1 <= max_chars <= MAX_DOM_CHARS:
                raise ToolError(f"max_chars must be between 1 and {MAX_DOM_CHARS}",
                                provider_id=self.id, code=ProviderErrorCode.VALIDATION)
            dump_path = params.get("save_html_path")
            if dump_path is not None:
                _optional_string(dump_path, "save_html_path", self.id)
                resolved = self.workspace.resolve(dump_path)
                if resolved.suffix.lower() not in {".html", ".htm"}:
                    raise ToolError("HTML dump path must end in .html or .htm",
                                    provider_id=self.id,
                                    code=ProviderErrorCode.VALIDATION)
            return

        if action_type == ActionType.BROWSER_CLICK.value:
            selector = params.get("selector")
            text = params.get("text")
            _optional_string(selector, "selector", self.id)
            _optional_string(text, "text", self.id)
            if bool(selector) == bool(text):
                raise ToolError("browser.click requires exactly one of selector or text",
                                provider_id=self.id, code=ProviderErrorCode.VALIDATION)
            return

        if action_type == ActionType.BROWSER_FILL.value:
            _required_string(params, "selector", self.id)
            text = params.get("text")
            value_ref = params.get("value_ref")
            if (text is None) == (value_ref is None):
                raise ToolError(
                    "browser.fill requires exactly one of text or value_ref",
                    provider_id=self.id, code=ProviderErrorCode.VALIDATION,
                )
            if text is not None and not isinstance(text, str):
                raise ToolError("browser.fill text must be a string", provider_id=self.id,
                                code=ProviderErrorCode.VALIDATION)
            if value_ref is not None:
                if not is_vault_ref(value_ref):
                    raise ToolError("browser.fill value_ref must be a vault reference",
                                    provider_id=self.id,
                                    code=ProviderErrorCode.VALIDATION)
                parsed = parse_vault_ref(value_ref)
                if parsed is None or parsed[0] != "browser":
                    raise ToolError("browser.fill value_ref must use the browser vault domain",
                                    provider_id=self.id,
                                    code=ProviderErrorCode.VALIDATION)
            return

        if action_type == ActionType.BROWSER_SUBMIT.value:
            _optional_string(params.get("selector"), "selector", self.id)

    def execute(self, action: Action, ctx: ExecutionContext) -> ActionResult:
        # Repeat all checks at the last responsible moment.  In particular this
        # repeats DNS/IP URL validation after authorization and before Chromium.
        self.validate(action)
        params = action.params or {}
        session_key = self._session_key(ctx)
        timeout_seconds = self.timeout_seconds
        if ctx.deadline is not None:
            remaining = ctx.deadline - time.monotonic() - _DISPATCH_SAFETY_MARGIN_SECONDS
            if remaining <= 0:
                raise ToolError("browser dispatch deadline exhausted", provider_id=self.id,
                                code=ProviderErrorCode.TIMEOUT)
            timeout_seconds = min(timeout_seconds, remaining)
        timeout_ms = max(1, int(timeout_seconds * 1000))
        action_type = action.action_type

        try:
            if action_type == ActionType.BROWSER_NAVIGATE.value:
                url = str(params["url"])
                validate_public_url(url)
                data = self.transport.navigate(
                    session_key, url,
                    wait_until=str(params.get("wait_until", "domcontentloaded")),
                    timeout_ms=timeout_ms,
                )
                return ActionResult(
                    success=True,
                    summary=f"navigated to {data.get('url', url)}",
                    data=_public_page_metadata(data),
                )

            if action_type == ActionType.BROWSER_SCREENSHOT.value:
                rel_path = str(params["path"])
                path = self.workspace.resolve(rel_path)
                suffix = path.suffix.lower()
                image_type = "jpeg" if suffix in {".jpg", ".jpeg"} else "png"
                image = self.transport.screenshot(
                    session_key,
                    selector=params.get("selector"),
                    full_page=bool(params.get("full_page", False)),
                    image_type=image_type,
                    timeout_ms=timeout_ms,
                )
                if not isinstance(image, bytes) or not image:
                    raise ToolError("browser returned an empty screenshot",
                                    provider_id=self.id,
                                    code=ProviderErrorCode.PROVIDER_ERROR)
                if len(image) > MAX_SCREENSHOT_BYTES:
                    raise ToolError("browser screenshot exceeds the size limit",
                                    provider_id=self.id,
                                    code=ProviderErrorCode.PROVIDER_ERROR)
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(image)
                return ActionResult(
                    success=True,
                    summary=f"saved browser screenshot to {rel_path}",
                    data={"path": self.workspace.path_of(path), "bytes": len(image)},
                )

            if action_type == ActionType.BROWSER_EXTRACT_DOM.value:
                raw = self.transport.extract(
                    session_key, selector=params.get("selector"), timeout_ms=timeout_ms,
                )
                return self._dom_result(raw, params)

            if action_type == ActionType.BROWSER_CLICK.value:
                data = self.transport.click(
                    session_key,
                    selector=params.get("selector"),
                    text=params.get("text"),
                    exact=bool(params.get("exact", False)),
                    timeout_ms=timeout_ms,
                )
                return ActionResult(success=True, summary="clicked browser element",
                                    data=_public_page_metadata(data))

            if action_type == ActionType.BROWSER_FILL.value:
                fill_text = self._resolve_fill_text(params, ctx)
                data = self.transport.fill(
                    session_key, selector=str(params["selector"]),
                    text=fill_text, timeout_ms=timeout_ms,
                )
                return ActionResult(success=True, summary="filled browser input",
                                    data=_public_page_metadata(data))

            if action_type == ActionType.BROWSER_SUBMIT.value:
                data = self.transport.submit(
                    session_key, selector=params.get("selector"), timeout_ms=timeout_ms,
                )
                return ActionResult(success=True, summary="submitted browser form",
                                    data=_public_page_metadata(data))
        except ToolError:
            raise
        except TimeoutError as exc:
            if action_type in self.non_retryable_action_types:
                self.close_context(ctx)
                raise ToolError(
                    "browser interaction outcome is unknown after timeout",
                    provider_id=self.id,
                    code=ProviderErrorCode.SIDE_EFFECT_UNKNOWN,
                ) from exc
            raise _transport_error(exc) from exc
        except OSError as exc:
            raise ToolError("browser workspace write failed", provider_id=self.id,
                            code=ProviderErrorCode.PROVIDER_ERROR) from exc
        except Exception as exc:
            raise _transport_error(exc) from exc

        raise ToolError(f"browser cannot handle {action_type}", provider_id=self.id,
                        code=ProviderErrorCode.NOT_IMPLEMENTED)

    def _resolve_fill_text(self, params: dict[str, Any], ctx: ExecutionContext) -> str:
        text = params.get("text")
        if isinstance(text, str):
            return text
        value_ref = str(params.get("value_ref", ""))
        if self._secret_resolver is None \
                or not hasattr(self._secret_resolver, "resolve_ref"):
            raise ToolError("browser vault resolver is unavailable", provider_id=self.id,
                            code=ProviderErrorCode.AUTH)
        try:
            resolved = self._secret_resolver.resolve_ref(
                value_ref, actor_id=ctx.actor_id, require_owner=True,
            )
        except VaultError as exc:
            raise ToolError("browser fill credential could not be resolved",
                            provider_id=self.id, code=ProviderErrorCode.AUTH) from exc
        if not isinstance(resolved, str):
            raise ToolError("browser fill credential resolved to an invalid value",
                            provider_id=self.id, code=ProviderErrorCode.AUTH)
        return resolved

    def close_context(self, ctx: ExecutionContext) -> None:
        """Discard one actor/session's ephemeral cookies and page state."""

        self.transport.close_context(self._session_key(ctx))

    def close(self) -> None:
        """Close all browser contexts and the underlying Chromium process."""

        self.transport.close()

    def describe(self) -> ProviderInfo:
        return ProviderInfo(
            id=self.id,
            action_types=self.action_types,
            version="0.8.1",
            display_name="Browser (self-hosted Playwright Chromium)",
            is_stub=False,
            capabilities=(
                "navigate", "screenshot", "dynamic-dom", "click", "fill", "submit",
                "ssrf-guarded", "isolated-contexts", "workspace-confined",
            ),
        )

    def _dom_result(self, raw: dict[str, Any], params: dict[str, Any]) -> ActionResult:
        max_chars = int(params.get("max_chars", DEFAULT_DOM_CHARS))
        html = str(raw.get("html", ""))
        source_truncated = len(html) > MAX_DOM_SOURCE_CHARS
        html = html[:MAX_DOM_SOURCE_CHARS]
        base_url = str(raw.get("url", ""))
        parser = _ReadableDOMParser(base_url)
        try:
            parser.feed(html)
        except Exception:  # noqa: BLE001,S110 - malformed live HTML is expected
            pass

        raw_text = str(raw.get("text", "")) or parser.text
        text = _clean_text(raw_text)[:max_chars]
        markdown = _clean_markdown(parser.markdown)[:max_chars]
        links = parser.links[:MAX_LINKS]
        data: dict[str, Any] = {
            "url": base_url,
            "title": str(raw.get("title", ""))[:500],
            "text": text,
            "markdown": markdown,
            "links": links,
            "text_chars": len(text),
            "markdown_chars": len(markdown),
            "source_truncated": source_truncated,
        }

        dump_path = params.get("save_html_path")
        if dump_path:
            path = self.workspace.resolve(str(dump_path))
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(html, encoding="utf-8")
            data["html_path"] = self.workspace.path_of(path)
            data["html_bytes"] = len(html.encode("utf-8"))

        return ActionResult(
            success=True,
            summary=(f"extracted {len(text)} text chars, {len(markdown)} markdown chars "
                     f"and {len(links)} link(s) from the browser DOM"),
            data=data,
        )

    @staticmethod
    def _session_key(ctx: ExecutionContext) -> str:
        actor = ctx.actor_id or "anonymous"
        scope = ctx.execution_scope or ctx.session_id or "default"
        material = f"{len(actor)}:{actor}|{len(scope)}:{scope}".encode()
        return hashlib.sha256(material).hexdigest()


class _ReadableDOMParser(HTMLParser):
    """Small dependency-free readable-text/Markdown/link extractor."""

    _BLOCKS = frozenset({
        "article", "aside", "blockquote", "div", "footer", "header", "main", "nav",
        "p", "section", "table", "tr",
    })
    _SKIP = frozenset({"script", "style", "noscript", "template", "svg"})

    def __init__(self, base_url: str):
        super().__init__(convert_charrefs=True)
        self.base_url = base_url
        self._skip_depth = 0
        self._markdown: list[str] = []
        self._text: list[str] = []
        self._anchor_stack: list[dict[str, Any]] = []
        self.links: list[dict[str, str]] = []

    @property
    def text(self) -> str:
        return " ".join(self._text)

    @property
    def markdown(self) -> str:
        return "".join(self._markdown)

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        tag = tag.lower()
        if tag in self._SKIP:
            self._skip_depth += 1
            return
        if self._skip_depth:
            return
        values = dict(attrs)
        if tag in self._BLOCKS:
            self._markdown.append("\n\n")
        elif tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
            self._markdown.append("\n\n" + "#" * int(tag[1]) + " ")
        elif tag == "li":
            self._markdown.append("\n- ")
        elif tag == "br":
            self._markdown.append("\n")
        elif tag in {"strong", "b"}:
            self._markdown.append("**")
        elif tag in {"em", "i"}:
            self._markdown.append("*")
        elif tag == "a":
            href = str(values.get("href") or "").strip()
            resolved = urljoin(self.base_url, href) if href else ""
            self._anchor_stack.append({"href": resolved, "text": []})
            self._markdown.append("[")

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        if tag in self._SKIP:
            if self._skip_depth:
                self._skip_depth -= 1
            return
        if self._skip_depth:
            return
        if tag == "a" and self._anchor_stack:
            anchor = self._anchor_stack.pop()
            href = anchor["href"]
            self._markdown.append(f"]({href})" if href else "]")
            if href and len(self.links) < MAX_LINKS:
                label = _clean_inline(" ".join(anchor["text"]))
                self.links.append({"text": label[:500], "url": href[:2048]})
        elif tag in {"strong", "b"}:
            self._markdown.append("**")
        elif tag in {"em", "i"}:
            self._markdown.append("*")
        elif tag in self._BLOCKS or tag.startswith("h") and len(tag) == 2:
            self._markdown.append("\n\n")

    def handle_data(self, data: str) -> None:
        if self._skip_depth:
            return
        clean = _clean_inline(data)
        if not clean:
            return
        self._text.append(clean)
        self._markdown.append(clean + " ")
        if self._anchor_stack:
            self._anchor_stack[-1]["text"].append(clean)


def _required_string(params: dict[str, Any], key: str, provider_id: str) -> str:
    value = params.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ToolError(f"'{key}' is required", provider_id=provider_id,
                        code=ProviderErrorCode.VALIDATION)
    return value.strip()


def _optional_string(value: Any, name: str, provider_id: str) -> None:
    if value is not None and (not isinstance(value, str) or not value.strip()):
        raise ToolError(f"'{name}' must be a non-empty string", provider_id=provider_id,
                        code=ProviderErrorCode.VALIDATION)


def _public_page_metadata(data: dict[str, Any]) -> dict[str, Any]:
    return {
        key: data[key]
        for key in ("url", "title", "status")
        if key in data and data[key] is not None
    }


def _clean_inline(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _clean_text(text: str) -> str:
    lines = [_clean_inline(line) for line in text.splitlines()]
    return "\n".join(line for line in lines if line)


def _clean_markdown(text: str) -> str:
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r" *\n *", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _title_from_html(html: str) -> str:
    match = re.search(r"<title[^>]*>(.*?)</title>", html, flags=re.IGNORECASE | re.DOTALL)
    return _clean_inline(re.sub(r"<[^>]+>", "", match.group(1))) if match else ""


def _plain_text_from_html(html: str) -> str:
    parser = _ReadableDOMParser("")
    try:
        parser.feed(html)
    except Exception:  # noqa: BLE001,S110
        pass
    return _clean_text(parser.text)
